blank_issues_enabled: false
contact_links:
  - name: 🚀 Reach out to us
    url: https://amakentech.com/contact
    about: If you have any questions or need assistance, please contact us using the above link.
